local command_palette = {
      {"File",
        { "entire selection (C-a)", ':call feedkeys("GVgg")' },
        { "save current file (C-s)", ':w' },
        { "save all files (C-A-s)", ':wa' },
        { "quit (C-q)", ':qa' },
        { "file browser (C-i)", ":lua require'telescope'.extensions.file_browser.file_browser()", 1 },
        { "search word (A-w)", ":lua require('telescope.builtin').live_grep()", 1 },
        { "git files (A-f)", ":lua require('telescope.builtin').git_files()", 1 },
        { "files (C-f)",     ":lua require('telescope.builtin').find_files()", 1 },
      },
      {"Help",
        { "tips", ":help tips" },
        { "cheatsheet", ":help index" },
        { "tutorial", ":help tutor" },
        { "summary", ":help summary" },
        { "quick reference", ":help quickref" },
        { "search help(F1)", ":lua require('telescope.builtin').help_tags()", 1 },
      },
      {"Vim",
        { "reload vimrc", ":source $MYVIMRC" },
        { 'check health', ":checkhealth" },
        { "jumps (Alt-j)", ":lua require('telescope.builtin').jumplist()" },
        { "commands", ":lua require('telescope.builtin').commands()" },
        { "command history", ":lua require('telescope.builtin').command_history()" },
        { "registers (A-e)", ":lua require('telescope.builtin').registers()" },
        { "colorshceme", ":lua require('telescope.builtin').colorscheme()", 1 },
        { "vim options", ":lua require('telescope.builtin').vim_options()" },
        { "keymaps", ":lua require('telescope.builtin').keymaps()" },
        { "buffers", ":Telescope buffers" },
        { "search history (C-h)", ":lua require('telescope.builtin').search_history()" },
        { "paste mode", ':set paste!' },
        { 'cursor line', ':set cursorline!' },
        { 'cursor column', ':set cursorcolumn!' },
        { "spell checker", ':set spell!' },
        { "relative number", ':set relativenumber!' },
        { "search highlighting (F12)", ':set hlsearch!' },
      },
      {"issue",
         { "close_issue", ":<space> ic" },
         { "reopen_issue", ":<space>io" },
         { "list_issues", ":<space>il" },
         { "reload", ":<C-r>" },
         { "open_in_browser", ":<C-b>" },
         { "copy_url", ":<C-y>" },
         { "add_assignee", ":<space>aa" },
         { "remove_assignee", ":<space>ad" },
         { "create_label", ":<space>lc" },
         { "add_label", ":<space>la" },
         { "remove_label", ":<space>ld" },
         { "goto_issue", ":<space>gi" },
         { "add_comment", ":<space>ca" },
         { "delete_comment", ":<space>cd" },
         { "next_comment", ":]c" },
         { "prev_comment", ":[c" },
         { "react_hooray", ":<space>rp" },
         { "react_heart", ":<space>rh" },
         { "react_eyes", ":<space>re" },
         { "react_thumbs_up", ":<space>r+" },
         { "react_thumbs_down", ":<space>r-" },
         { "react_rocket", ":<space>rr" },
         { "react_laugh", ":<space>rl" },
         { "react_confused", ":<space>rc" },
        },
        {"pull_request",
         { "checkout_pr", ":<space>po" },
         { "merge_pr", ":<space>pm" },
         { "squash_and_merge_pr", ":<space>psm" },
         { "list_commits", ":<space>pc" },
         { "list_changed_files", ":<space>pf" },
         { "show_pr_diff", ":<space>pd" },
         { "add_reviewer", ":<space>va" },
         { "remove_reviewer", ":<space>vd" },
         { "close_issue", ":<space>ic" },
         { "reopen_issue", ":<space>io" },
         { "list_issues", ":<space>il" },
         { "reload", ":<C-r>" },
         { "open_in_browser", ":<C-b>" },
         { "copy_url", ":<C-y>" },
         { "goto_file", ":gf" },
         { "add_assignee", ":<space>aa" },
         { "remove_assignee", ":<space>ad" },
         { "create_label", ":<space>lc" },
         { "add_label", ":<space>la" },
         { "remove_label", ":<space>ld" },
         { "goto_issue", ":<space>gi" },
         { "add_comment", ":<space>ca" },
         { "delete_comment", ":<space>cd" },
         { "next_comment", ":]c" },
         { "prev_comment", ":[c" },
         { "react_hooray", ":<space>rp" },
         { "react_heart", ":<space>rh" },
         { "react_eyes", ":<space>re" },
         { "react_thumbs_up", ":<space>r+" },
         { "react_thumbs_down", ":<space>r-" },
         { "react_rocket", ":<space>rr" },
         { "react_laugh", ":<space>rl" },
         { "react_confused", ":<space>rc" },
       },
       { "review_thread",
         { "goto_issue", ":<space>gi" },
         { "add_comment", ":<space>ca" },
         { "add_suggestion", ":<space>sa" },
         { "delete_comment", ":<space>cd" },
         { "next_comment", ":]c" },
         { "prev_comment", ":[c" },
         { "select_next_entry", ":]q" },
         { "select_prev_entry", ":[q" },
         { "close_review_tab", ":<C-c>" },
         { "react_hooray", ":<space>rp" },
         { "react_heart", ":<space>rh" },
         { "react_eyes", ":<space>re" },
         { "react_thumbs_up", ":<space>r+" },
         { "react_thumbs_down", ":<space>r-" },
         { "react_rocket", ":<space>rr" },
         { "react_laugh", ":<space>rl" },
         { "react_confused", ":<space>rc" },
       },
       {"submit_win",
         { "approve_review", ":<C-a>" },
         { "comment_review", ":<C-m>" },
         { "request_changes", ":<C-r>" },
         { "close_review_tab", ":<C-c>" },
       },
       {"review_diff",
         { "add_review_comment", ":<space>ca" },
         { "add_review_suggestion", ":<space>sa" },
         { "focus_files", ":<leader>e" },
         { "toggle_files", ":<leader>b" },
         { "next_thread", ":]t" },
         { "prev_thread", ":[t" },
         { "select_next_entry", ":]q" },
         { "select_prev_entry", ":[q" },
         { "close_review_tab", ":<C-c>" },
         { "toggle_viewed", ":<leader><space>" },
       },
       {"file_panel",
         { "next_entry", ":j" },
         { "prev_entry", ":k" },
         { "select_entry", ":<cr>" },
         { "refresh_files", ":R" },
         { "focus_files", ":<leader>e" },
         { "toggle_files", ":<leader>b" },
         { "select_next_entry", ":]q" },
         { "select_prev_entry", ":[q" },
         { "close_review_tab", ":<C-c>" },
         { "toggle_viewed", ":<leader><space>" },
       }
    }

return command_palette
